name: 02 - Workflow events

on: 
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "This workflow was triggered by event: ${{ github.event_name }}"

