name: 06 - Contexts ENV
run-name: "06 - Contexts - ${{ inputs.debug }}" 
on: 
  workflow_dispatch:
    inputs:
      debug:
        description: 'A variable to be used in the workflow'
        required: true
        type: boolean
        default: false
env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
  echo-data:
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        env:
          MY_STEP_VAR: 'step'
          MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Job ID: ${{ github.job }}"
          echo "MY_OVERWRITTEN_VAR var: ${{ env.MY_OVERWRITTEN_VAR }}"
      - name: Retrieve Variable
        run: |
          echo "Print the value from repository variable ${{ vars.MY_VAR}}"
          echo "Job MY_OVERWRITTEN_VAR var: ${{ env.MY_OVERWRITTEN_VAR }}"
  echo-data-2:
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        run: |
          echo "Print the value from repository variable ${{ vars.MY_VAR}}"
          echo "Job MY_OVERWRITTEN_VAR var: ${{ env.MY_OVERWRITTEN_VAR }}"
          echo "Job MY_OVERWRITTEN_VAR var: $MY_OVERWRITTEN_VAR"
          