name: 06 - Contexts
on: 
  - workflow_dispatch
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Job ID: ${{ github.job }}"
      - name: Retrieve Variable
        run: echo "Print the value from repository variable ${{ vars.MY_VAR}}"
