name: "07 - expressions - Debug"
run-name: 07 - expressions - Debug - ${{ inputs.debug && 'ON' || 'OFF' }}


on: 
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
  MY_WORKFLOW_VAR: ${{ vars.MY_VAR || 'default' }}


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug == true }}
        run: |
          echo  "Triggered by: ${{ github.event_name }}"    
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "ENV var: ${{ env.MY_WORKFLOW_VAR }}"
          echo "ENV var: ${{ env.MY_WORKFLOW_VAR || 'not set' }}"
      - name: "[debug] Print when triggered from main"
        if: ${{ inputs.debug  == true && github.ref_name == 'main' }}
        run: |
          echo "I was triggered from main"
      - name: "Greeting"
        run: |
          echo "Hello, world"