name: 11 - Working with Inputs

on: 
    workflow_call:
    workflow_dispatch:
        inputs:
            dry-run:
                description: "Skip deployment and only print build output"
                type: boolean
                default: false
            target:
                description: "Which environment the workflow will target"
                type: environment
                required: true
            tags:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
                description: "Release from which to build and deploy"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building from tag ${{ inputs.tags }}"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ inputs.dry-run == false }}  
        environment: ${{ inputs.target }}
        steps:
            - name: Deploy
              run: echo "Deploying to ${{ inputs.target }}"
            
