name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Print GITHUB_OUTPUT path
              run: |
                echo "GITHUB_OUTPUT : $GITHUB_OUTPUT"
            - name: Build
              id: stepId
              run: |
                    echo "Building..."
                    echo "output1=value1" >> $GITHUB_OUTPUT
                    echo "output2=value2" >> $GITHUB_OUTPUT
                    cat $GITHUB_OUTPUT
                    echo "mistake=true" >> "$GITHUB_OUTPUT"
                    cat $GITHUB_OUTPUT
            - name: Step with mistake
              id: stepId1
              run: |
                echo "output2=value3" >> "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"
        outputs:
            output1: ${{ steps.stepId.outputs.output1 }}
            output2: ${{ steps.stepId.outputs.output2 }}
            stepid1_output2: ${{ steps.stepId1.outputs.output2 }}
            
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy if success
              if: ${{ needs.build.outputs.output1 == 'success' }}
              run: echo "Deploying... ${{needs.build.outputs.output1}}"
            - name: Deploy if failure
              if: ${{ needs.build.outputs.output1 == 'failure' }}
              run: echo "Deploying... ${{needs.build.outputs.output1}}"
            - name: Print outputs
              run: |
                echo "build job- stepid - output1: ${{needs.build.outputs.output1}}"
                echo "build job- stepid - output2: ${{needs.build.outputs.output2}}"
                echo "build job- stepid1 - output2: ${{needs.build.outputs.stepid1_output2}}"
