name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.build-status }}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: |
                echo "GITHUB_OUTPUT : ${{env.GITHUB_OUTPUT}}"
            - name: Build
              id: build
              run: |
                    echo "Building..."
                    echo "build-status=Success" >> $GITHUB_OUTPUT
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build-status == 'Success' }}
        steps:
            - name: Deploy
              run: echo "Deploying..."          