name: 16 - Working with Environments

on: 
    workflow_dispatch:
jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: "Echo vars"
              run: echo "Deploying on staging"
    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-staging
        steps:
            - name: "Echo vars"
              run: echo "Deploying on prod"   
    deploy-prod:
        runs-on: ubuntu-latest
        needs: e2e-tests
        environment: prod
        steps:
            - name: "Echo vars"
              run: echo "Deploying on prod"        